package com.dhananjaysaini.musicplayerapp.constants

object Constants {

    const val CHANNEL_ID = "MUSIC_PLAYER_CHANNEL"
    const val NOTIFICATION_ID = 1001

    const val ACTION_PLAY = "ACTION_PLAY"
    const val ACTION_PAUSE = "ACTION_PAUSE"
    const val ACTION_NEXT = "ACTION_NEXT"
    const val ACTION_PREVIOUS = "ACTION_PREVIOUS"

    const val ACTION_PLAY_NEW_LIST = "ACTION_PLAY_NEW_LIST"
    const val ACTION_PLAY_AT = "ACTION_PLAY_AT"
    const val ACTION_SEEK_TO = "ACTION_SEEK_TO"
    const val ACTION_REFRESH_NOTIFICATION = "ACTION_REFRESH_NOTIFICATION"

    const val ACTION_TOGGLE_PLAY = "ACTION_TOGGLE_PLAY"
    const val ACTION_PLAY_NEW = "ACTION_PLAY_NEW"

    const val ACTION_START_TIMER = "ACTION_START_TIMER"
    const val ACTION_CANCEL_TIMER = "ACTION_CANCEL_TIMER"

    const val ACTION_TIMER_UPDATE = "ACTION_TIMER_UPDATE"
    const val EXTRA_TIMER_TIME = "EXTRA_TIMER_TIME"
    const val EXTRA_REMAINING_TIME = "EXTRA_REMAINING_TIME"
    const val ACTION_MUSIC_STOPPED_BY_TIMER = "ACTION_MUSIC_STOPPED_BY_TIMER"

}